version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      all:
        applies-to: version-updates

  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: daily
    versioning-strategy: lockfile-only
    open-pull-requests-limit: 10
    groups:
      dev-dependencies:
        dependency-type: "development"
      prod-dependencies:
        dependency-type: "production"