services:
  db:
    image: ghcr.io/tweedegolf/postgres:16
    environment:
      POSTGRES_USER: openadr
      POSTGRES_DB: openadr
      TZ: Europe/Amsterdam
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U openadr"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports: [ "127.0.0.1:5432:5432" ]