services:
  vtn:
    build:
      dockerfile: vtn.Dockerfile
      context: .
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      RUST_LOG: debug
    healthcheck:
      test: curl --fail http://127.0.0.1:3000/programs || exit 1
      interval: 60s
      timeout: 5s
      retries: 3