services:
  db:
    image: ghcr.io/tweedegolf/postgres:16
    environment:
      POSTGRES_USER: openadr
      POSTGRES_DB: openadr
      TZ: Europe/Amsterdam
      POSTGRES_HOST_AUTH_METHOD: trust
    ports: [ "127.0.0.1:5432:5432" ]